# Generated by Django 5.2.18 on 2026-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('entities', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
