# Generated by Django 5.2.18 on 2026-10-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
    ]
