# Generated by Django 5.2.18 on 2026-10-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0002_crawledpage_risk_level_crawledpage_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
