# Generated by Django 5.2.18 on 2026-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_app', '0003_crawledpage_screenshot_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledpage',
            name='ai_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_risk_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crawledpage',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
